apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  annotations:
    kpack.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: '<username>'
  password: '<password>'

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service-account
  namespace: default
secrets:
  - name: docker-credentials
imagePullSecrets:
  - name: docker-credentials
